Added exception monitoring client
scoutapp/scout-apm-php pull request #243
Opened 2021-10-28 12:04 UTC by asgrim

## Dependencies on HTTP client

This adds a dependency on `php-http/discovery`. For this to work, you would already need an HTTP client installed, or install a compatible client.

If you receive an error, such as:

```
In ScoutErrorHandling.php line 66:
                                                         
  Class "Http\Discovery\Psr18ClientDiscovery" not found  
```

You need to resolve the HTTP discovery dependency, because your installed packages do not satisfy the requirement.

For example, if you are on PHP 7.1 and need Guzzle 6, `composer require php-http/guzzle6-adapter nyholm/psr7` will fulfill the dependencies.

On PHP 7.2+, `composer require guzzlehttp/guzzle:^7.0` is already compatible.

## Configuration

By default, error reporting is not enabled at the moment. To enable, you should add `errors_enabled` configuration with a boolean `true`:

```sh
SCOUT_ERRORS_ENABLED=true
```

## Laravel 5/6/7

In order to capture errors, in your `\App\Exceptions\Handler::report` function in your application:

```php
    /**
     * Report or log an exception.
     *
     * @param  \Exception  $exception
     * @return void
     */
    public function report(Exception $exception)
    {
        $this->container->make(\Scoutapm\ScoutApmAgent::class)->recordThrowable($exception); // <-- add this line
        parent::report($exception);
    }
```

## Laravel 8

In order to capture errors, in your `\App\Exceptions\Handler::register` function in your application:

```php
    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            $this->container->make(ScoutApmAgent::class)->recordThrowable($e);
        });
    }
```

## Lumen

In order to capture errors, in your `\App\Exceptions\Handler::report` function in your application:

```php
    /**
     * Report or log an exception.
     *
     * This is a great spot to send exceptions to Sentry, Bugsnag, etc.
     *
     * @param  \Throwable  $exception
     * @return void
     *
     * @throws \Exception
     */
    public function report(Throwable $exception)
    {
        app(\Scoutapm\ScoutApmAgent::class)->recordThrowable($exception);
        parent::report($exception);
    }
```

## Symfony

Exception listening is provided out the box, so no additional code is needed for Symfony. However, since Symfony already has an HTTP Client out the box, you would need to install something like `composer require php-http/httplug nyholm/psr7` to enable the PSR-18 HTTP Client auto discovery to use it.

2021-12-08 16:48 UTC, Ocramius requested changes

2021-12-08 16:48 UTC, Ocramius commented on src/Errors/ScoutErrorHandling.php
> +        register_shutdown_function([$this, 'handleShutdown']);
Will other shutdown functions be used / still work?

2021-12-08 16:48 UTC, Ocramius commented on src/Errors/ScoutErrorHandling.php
> +        $ignoredExceptions = $this->config->get(Config\ConfigKey::ERRORS_IGNORED_EXCEPTIONS);
The pattern of `$this->config->get(...): mixed` is quite draining for this codebase - perhaps there's a better way, to avoid type-checking in all consumers?  :thinking:

2021-12-08 16:48 UTC, Ocramius commented on src/Errors/ScoutErrorHandling.php
> +        $this->errorEvents[] = ErrorEvent::fromThrowable($this->request, $throwable);
Don't fully understand why this method populates `errorEvents[]`, then immediately calls `sendCollectedErrors()`, which will clear it.

Also, if `! $this->errorsEnabled()`, then there's a (potential) risk that this list will only ever grow.

Since we don't seem to really accumulate any errors at all, it is perhaps better to just directly send everything to ScoutAPM, and remove the accumulator class property.

2021-12-08 16:48 UTC, Ocramius commented on src/Events/Request/Request.php
> +        /** @todo this should be injected! */
Was going to comment on this, then noticed the TODO: really worth doing this!

2021-12-08 16:48 UTC, Ocramius commented on src/Events/Request/Request.php
> +        return reset($controllerOrJobSpanNames);
`reset()` is a bit fiddly - perhaps using `array_values()` and then the key `0` of the resulting array? Non-blocker though.

2021-12-08 16:48 UTC, Ocramius commented on src/Helper/FilterParameters.php
> +     * @psalm-template T as int
Are values `>4` supposed to ever supposed to make it through? (potentially yes, but worth asking)

2021-12-08 16:48 UTC, Ocramius commented on src/Helper/FilterParameters.php
> +     * @psalm-template T as int
This value should probably be `postive-int`, since `0` doesn't seem to be handled below

2021-12-08 16:48 UTC, Ocramius commented on src/Helper/FindApplicationRoot/FindApplicationRootWithConfigOverride.php
> +        $composerJsonLocation = $this->locateFileOrFolder->__invoke('composer.json');
This does a file lookup each time (for every event), which could be quite taxing for a runtime application: perhaps worth caching this information locally? Application path doesn't change in a single request, does it?

2021-12-08 16:48 UTC, Ocramius commented on src/Helper/LocateFileOrFolder/LocateFileOrFolderUsingFilesystem.php
> +        while (dirname($dir) !== $dir && $dir !== $rootOrHome) {
Not a blocker, but recursion could kinda help here :D

2021-12-08 16:48 UTC, Ocramius commented on src/Helper/LocateFileOrFolder/LocateFileOrFolderUsingFilesystem.php
> +            if (file_exists($fileOrFolderAttempted) && is_readable($fileOrFolderAttempted)) {
perhaps `is_file()`? Do we care about readability?

2021-12-08 16:48 UTC, Ocramius commented on src/Helper/RootPackageGitSha/FindRootPackageGitShaWithHerokuAndConfigOverride.php
> +        $herokuSlugCommit = getenv('HEROKU_SLUG_COMMIT');
Perhaps `$this->config` could already have this? Non-blocker, but a bit weird to read this here.

2021-12-08 16:48 UTC, Ocramius commented on src/Helper/RootPackageGitSha/FindRootPackageGitShaWithHerokuAndConfigOverride.php
> +        return '';
Is it worth returning something like `version not detected` here?

2021-12-08 16:48 UTC, Ocramius commented on src/Helper/RootPackageGitSha/FindRootPackageGitShaWithHerokuAndConfigOverride.php
> +        $herokuSlugCommit = getenv('HEROKU_SLUG_COMMIT');
Perhaps injecting `Superglobals` and reading out `env()` from there?

2021-12-08 16:48 UTC, Ocramius commented on src/Laravel/Facades/ScoutApm.php
> + * @method static void recordThrowable(Throwable $throwable)
Does the `ScoutApm` Laravel static singleton service locator proxy through everythin defined on `ScoutApmAgent`? If so, we could potentially use `@mixin ScoutApmAgent`, but unsure if it details the methods as `static`

2021-12-28 11:57 UTC, asgrim commented on composer.json
>          "ext-sockets": "*",
Yes, still needed; we talk to the main APM `core-agent` via sockets.

2021-12-28 12:00 UTC, asgrim commented on .github/workflows/laravel.yml
> +          composer require --dev php-http/guzzle6-adapter --no-update --no-interaction
Since Guzzle is so widely used, I'd prefer to run our test suite using it; the main pain from maintenance perspective is supporting PHP 7.1 through PHP 8.0 (currently), hence the need to fiddle the dependencies for PHP 7.1. Dropping PHP 7.1 support is out of scope here for sure.

2021-12-28 12:02 UTC, asgrim commented on CHANGELOG.md
> +  - Class `Scoutapm\Helper\LocateFileOrFolder` became an interface (with default implementation) and marked `@internal`
Fixed

2021-12-28 12:07 UTC, asgrim commented on composer.json
> +        "psr/http-message": "^1.0",
This is intentional and by design. The error reporting component is entirely optional, so we do not force users to install these additional dependencies. They are marked in `suggests` and will be documented. Unfortunately, yes - that means the requirement is shifted into runtime.

If the end user explicitly enables the configuration option for this feature, but they have not installed the required dependencies, then they will receive the following warning in the logs, and no error handling will be enabled.

https://github.com/scoutapp/scout-apm-php/blob/676fd8547c3f52c5ae087ca122bb1edaa1813a73/src/Errors/ErrorHandlingDiscoveryFactory.php#L56-L80

If a customer enables the setting, and is not seeing the error reporting in their dashboard, support will be able to look for this warning if they ask for the customer's logs, and provide recommendation to install the required dependency.

(cc @dlanderson & @jrothrock )

2021-12-28 12:07 UTC, asgrim commented on composer.json
> +        "psr/http-client-implementation": "Required for Scout Error Reporting",
Discussion in https://github.com/scoutapp/scout-apm-php/pull/243#discussion_r775876480 - closing as duplicate

2021-12-28 12:08 UTC, asgrim commented on .github/workflows/tests.yml
> +          composer remove --dev guzzlehttp/guzzle --no-update --no-interaction
Discussion in https://github.com/scoutapp/scout-apm-php/pull/243#discussion_r775876480 - closing as duplicate

2021-12-28 12:14 UTC, asgrim commented on composer.json
>          "ext-zlib": "*",
I actually dropped this in 1d90c537b6d7e814318f0772630fa6a206d10f5d since it made having such a wide supported PHP version almost impossible; I think I couldn't set up an installable set of packages with that in, IIRC. The wide PHP version support is really a headache, and it was the only way I could get it to work I think.

2021-12-28 12:16 UTC, asgrim commented on known-issues.xml
> +    <ParamNameMismatch occurrences="1">
When we add support for PHP 8.1, all interfaces (including [`CoerceType`](https://github.com/scoutapp/scout-apm-php/pull/235/files#diff-0c73dbc5cb23e88bfb84ead5730b3fb1ee5506e6580a86258fc6d12a17e88881R15)) will be marked with `@no-named-arguments`

2021-12-28 12:16 UTC, asgrim commented on known-issues.xml
> +    <ParamNameMismatch occurrences="1">
As above

2021-12-28 12:17 UTC, asgrim commented on known-issues.xml
> +      <code>$span</code>
As above, we will nave `@no-named-arguments` added

2021-12-28 12:25 UTC, asgrim commented on src/Agent.php
> +        $this->errorHandling->registerListeners();
Aye, not a fan of side-effects in constructors, but it is by design; the goal is to have end customer do as little as possible to get the functionality offered. The goal is very much "make it simple".

2021-12-28 12:27 UTC, asgrim commented on src/Agent.php
> +        $this->findRequestHeaders = new FindRequestHeadersUsingServerGlobal($superglobals);
Fixed

2021-12-28 12:28 UTC, asgrim commented on src/Config/Helper/RequireValidFilteredParameters.php
> +final class RequireValidFilteredParameters
Fixed

2021-12-28 12:31 UTC, asgrim commented on src/Errors/ErrorEvent.php
> + * @psalm-type ErrorEventJsonableArray = array{
Fixed

2021-12-28 12:32 UTC, asgrim commented on src/Errors/ErrorEvent.php
> +     * @psalm-param class-string $exceptionClass
Fixed

2021-12-28 12:39 UTC, asgrim commented on src/Errors/ErrorEvent.php
> +        // phpcs:disable SlevomatCodingStandard.PHP.UselessParentheses.UselessParentheses
Fixed

2021-12-28 12:42 UTC, asgrim commented on src/Errors/ErrorEvent.php
> +        $controllerName = explode(
We do our best to try and determine controller name from various sources indeed. I've added protection against those keys being undefined though, good call.

2021-12-28 12:43 UTC, asgrim commented on src/Errors/ErrorEvent.php
> +            'request_id' => $this->request ? $this->request->id()->toString() : null,
Leaving as-is.

2021-12-28 12:48 UTC, asgrim commented on src/Errors/ErrorHandling.php
> +    public function changeCurrentRequest(Request $request): void;
Fixed

2021-12-28 12:49 UTC, asgrim commented on src/Errors/ScoutClient/CompressPayload.php
> +class CompressPayload
I could not get this to work according to the server's expectations :/ it works, so will leave as is.

2021-12-28 12:50 UTC, asgrim commented on src/Errors/ScoutClient/HttpErrorReportingClient.php
> +            $response = $this->client->sendRequest($this->psrRequestFromEvents($errorEvents));
It is something we plan to improve in future - see #245

2021-12-28 12:54 UTC, asgrim commented on src/Errors/ScoutClient/HttpErrorReportingClient.php
> +            ->withHeader('Content-Encoding', 'gzip') // Must be gzipped
Possible improvement in future; created #250

2021-12-28 12:54 UTC, asgrim commented on src/Errors/ScoutClient/CompressPayload.php
> +class CompressPayload
Added #250 to investigate future improvement.

2021-12-28 12:59 UTC, asgrim commented on src/Errors/ScoutErrorHandling.php
> +        $ignoredExceptions = $this->config->get(Config\ConfigKey::ERRORS_IGNORED_EXCEPTIONS);
Yeah, probably. Out of scope here, so created #251 - good call though, it's always causing pain to maintain.

2021-12-28 13:00 UTC, asgrim commented on src/Errors/ScoutErrorHandling.php
> +        $this->errorEvents[] = ErrorEvent::fromThrowable($this->request, $throwable);
The goal eventually is to support "batches" of errors; so this is generally for anticipated future features.

2021-12-28 13:32 UTC, asgrim commented on src/Events/Request/Request.php
> +        /** @todo this should be injected! */
Fixed

2021-12-28 13:32 UTC, asgrim commented on src/Events/Request/Request.php
> +        return reset($controllerOrJobSpanNames);
Fixed

2021-12-28 13:34 UTC, asgrim commented on src/Helper/FilterParameters.php
> +     * @psalm-template T as int
> Are values `>4` supposed to ever supposed to make it through? (potentially yes, but worth asking)

Yes, but I think by that point it is edge case territory (hence just returns `array`) in that case.

> This value should probably be `postive-int`, since `0` doesn't seem to be handled below

Fixed

2021-12-28 14:02 UTC, asgrim commented on src/Helper/FilterParameters.php
> +     * @psalm-template T as int
Oh, that was interesting. Possible bug discovered: vimeo/psalm#7235

2021-12-28 14:05 UTC, asgrim commented on src/Helper/LocateFileOrFolder/LocateFileOrFolderUsingFilesystem.php
> +        while (dirname($dir) !== $dir && $dir !== $rootOrHome) {
Leaving as-is

2021-12-28 14:14 UTC, asgrim commented on src/Helper/FindApplicationRoot/FindApplicationRootWithConfigOverride.php
> +        $composerJsonLocation = $this->locateFileOrFolder->__invoke('composer.json');
Fixed

2021-12-28 14:17 UTC, asgrim commented on src/Helper/LocateFileOrFolder/LocateFileOrFolderUsingFilesystem.php
> +            if (file_exists($fileOrFolderAttempted) && is_readable($fileOrFolderAttempted)) {
Not gonna change now, existing code just being moved.

2021-12-28 14:25 UTC, asgrim commented on src/Helper/RootPackageGitSha/FindRootPackageGitShaWithHerokuAndConfigOverride.php
> +        $herokuSlugCommit = getenv('HEROKU_SLUG_COMMIT');
> Perhaps `$this->config` could already have this? Non-blocker, but a bit weird to read this here.

`$this->config` only pulls things prefixed with `SCOUT_` in env, so can't be used for this.

> Perhaps injecting `Superglobals` and reading out `env()` from there?

This is a good shout though, fixed!

2021-12-28 14:26 UTC, asgrim commented on src/Helper/RootPackageGitSha/FindRootPackageGitShaWithHerokuAndConfigOverride.php
> +        return '';
Upstream uses empty string as an indication there is no git sha detected, #wontfix

2021-12-28 14:27 UTC, asgrim commented on src/Laravel/Facades/ScoutApm.php
> + * @method static void recordThrowable(Throwable $throwable)
No, the methods are not `static` in `ScoutApmAgent`. But yes, it basically proxies it, but it proxies to instance methods, not `static` :shrug:

2021-12-28 14:30 UTC, asgrim commented on .github/fixtures/laravel5-6-exception-handler.php
> +     * @var array
Not changing these; they are code which is in the Laravel skeleton, but with the scout error handler added. My choice was to either inject the required with `sed` or similar techniques, or just copy/pasta the whole file into here. Alternative approach suggestions welcome!

2021-12-28 14:30 UTC, asgrim commented on .github/fixtures/laravel5-6-exception-handler.php
> +     * @var array
See discussion: https://github.com/scoutapp/scout-apm-php/pull/243#discussion_r775934395

2021-12-28 14:30 UTC, asgrim commented on .github/fixtures/laravel7-exception-handler.php
> +     * @var array
https://github.com/scoutapp/scout-apm-php/pull/243#discussion_r775934395

2021-12-28 14:30 UTC, asgrim commented on .github/fixtures/laravel8-exception-handler.php
> +     * @var array
https://github.com/scoutapp/scout-apm-php/pull/243#discussion_r775934395

2021-12-28 14:33 UTC, asgrim commented on src/Config/Helper/RequireValidFilteredParameters.php
> +            if (! is_string($filteredParameter)) {
Fixed.

2021-12-28 14:36 UTC, asgrim commented on src/Errors/ErrorEvent.php
> + *      request_params?: array<string,string|array<array-key,string|array<array-key,string|array<array-key,string>>>>,
Yes - the call to `\Scoutapm\Helper\FilterParameters::flattenedForUriReportingConfiguration` on L162 with `$depth` set to `4` will ensure anything deeper than 4 levels will be flattened, so the shape fits. Anything higher than that will be collapsed into a string with value `array`. Not ideal, but I think they would be edge cases, and we can investigate that if it is reported.

2021-12-28 14:38 UTC, asgrim commented on src/Errors/ScoutClient/HttpErrorReportingClient.php
> +    private $memoizedErrorsUrl;
Fixed

2021-12-28 14:41 UTC, asgrim commented on src/Errors/ScoutErrorHandling.php
> +        register_shutdown_function([$this, 'handleShutdown']);
Yes, from docs for [register_shutdown_function](https://www.php.net/manual/en/function.register-shutdown-function.php):

> If you call `exit()` within one registered shutdown function, processing will stop completely and no other registered shutdown functions will be called.

We do not call `exit()`, so the assumption is any other registered handlers will run as usual.

2021-12-28 15:02 UTC, asgrim commented
CI pipeline failure is due to API endpoint is returning HTTP 429 currently - I've let @dlanderson know on Slack, does not appear to be related to code changes made here.

2021-12-29 16:37 UTC, Ocramius commented on composer.json
> +        "psr/http-message": "^1.0",
Discussed in call with @asgrim: the implementation in the factory is extremely lax, and behaves in a way that prevents a hard failure in case of not found dependencies.

It's a bit of overhead, and it is not the best solution for upgrading dependencies, but in the grand vision of keeping the component optional, it makes sense as-is.

2021-12-29 16:38 UTC, Ocramius commented on .github/fixtures/laravel5-6-exception-handler.php
> +     * @var array
Discussed with @asgrim in person: these files are generated by laravel's scaffolding tools, and these are just examples.

We don't need to touch these, nor try to improve the code quality, as we can do nothing about Laravel's protracted practices.

2021-12-29 16:44 UTC, Ocramius commented on composer.json
>          "ext-zlib": "*",
As discussed with @asgrim in person:

 * `composer.lock` is **not** considered while running `php:7.1` builds
 * if @dependabot is configured, we can tell it to **only** update `composer.lock`, and to only ever **expand** supported ranges (rather than bumping minimum supported versions)

Therefore, removing `config.platform.php` is fine

2021-12-29 16:48 UTC, Ocramius commented on src/Agent.php
> +        $this->errorHandling->registerListeners();
Discussed with @asgrim

The auto-configure detail comes out-of-the-box with symfony and laravel.

For consumers using `scoutapp/scout-apm-php` manually, they would instantiate the `Agent` on their own, then be confused by why the error handler changed due to the `Agent` modifying global state.

Suggestions here are:

 * `(new Agent)->selfRegister()`
 * `Agent::createAndRegister()`

Both don't violate the principle of least possible astonishment

2022-01-11 11:40 UTC, asgrim commented on src/Agent.php
> +        $this->errorHandling->registerListeners();
Moved the `registerListeners()` call into `\Scoutapm\Errors\ErrorHandlingDiscoveryFactory::createAndListen` constructor (which is used by default). Keeps the same observable behaviour, but it is overridable by injecting your own `ErrorHandler` into `Agent::fromConfig(...)`.

2022-01-11 11:40 UTC, asgrim commented
BC failures are expected; preparing for `7.0.0` release.

2022-01-11 12:01 UTC, merged